// Configuration des plateformes OAuth
export const PLATFORM_CONFIGS = {
  garmin: {
    name: 'Garmin Connect',
    authUrl: 'https://connect.garmin.com/oauthConfirm',
    tokenUrl: 'https://connectapi.garmin.com/oauth-service/oauth/access_token',
    apiBaseUrl: 'https://apis.garmin.com/wellness-api/rest',
    workoutApiUrl: 'https://apis.garmin.com/training-api/workout',
    scopes: ['ACTIVITY_IMPORT', 'ACTIVITY_EXPORT'],
    clientId: process.env.GARMIN_CLIENT_ID || '',
    clientSecret: process.env.GARMIN_CLIENT_SECRET || '',
    redirectUri: process.env.GARMIN_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/garmin/callback',
  },
  strava: {
    name: 'Strava',
    authUrl: 'https://www.strava.com/oauth/authorize',
    tokenUrl: 'https://www.strava.com/oauth/token',
    apiBaseUrl: 'https://www.strava.com/api/v3',
    scopes: ['activity:write', 'activity:read_all', 'read'],
    clientId: process.env.STRAVA_CLIENT_ID || '',
    clientSecret: process.env.STRAVA_CLIENT_SECRET || '',
    redirectUri: process.env.STRAVA_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/strava/callback',
  },
  suunto: {
    name: 'Suunto',
    authUrl: 'https://cloudapi-oauth.suunto.com/oauth/authorize',
    tokenUrl: 'https://cloudapi-oauth.suunto.com/oauth/token',
    apiBaseUrl: 'https://cloudapi.suunto.com/v2',
    scopes: ['workout', 'activity'],
    clientId: process.env.SUUNTO_CLIENT_ID || '',
    clientSecret: process.env.SUUNTO_CLIENT_SECRET || '',
    redirectUri: process.env.SUUNTO_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/suunto/callback',
  },
  coros: {
    name: 'COROS',
    authUrl: 'https://open.coros.com/oauth/authorize',
    tokenUrl: 'https://open.coros.com/oauth/token',
    apiBaseUrl: 'https://open.coros.com/v1',
    scopes: ['training:write', 'activity:read'],
    clientId: process.env.COROS_CLIENT_ID || '',
    clientSecret: process.env.COROS_CLIENT_SECRET || '',
    redirectUri: process.env.COROS_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/coros/callback',
  },
  polar: {
    name: 'Polar Flow',
    authUrl: 'https://flow.polar.com/oauth2/authorization',
    tokenUrl: 'https://polarremote.com/v2/oauth2/token',
    apiBaseUrl: 'https://www.polaraccesslink.com/v3',
    scopes: ['accesslink.read_all', 'training.write'],
    clientId: process.env.POLAR_CLIENT_ID || '',
    clientSecret: process.env.POLAR_CLIENT_SECRET || '',
    redirectUri: process.env.POLAR_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/polar/callback',
  },
  decathlon: {
    name: 'Decathlon Coach',
    authUrl: 'https://api-global.decathlon.net/connect/oauth/authorize',
    tokenUrl: 'https://api-global.decathlon.net/connect/oauth/token',
    apiBaseUrl: 'https://api-global.decathlon.net/sportstrackingdata/v2',
    scopes: ['activities', 'workouts'],
    clientId: process.env.DECATHLON_CLIENT_ID || '',
    clientSecret: process.env.DECATHLON_CLIENT_SECRET || '',
    redirectUri: process.env.DECATHLON_REDIRECT_URI || 'http://localhost:3001/api/platforms/oauth/decathlon/callback',
  },
};

export type Platform = keyof typeof PLATFORM_CONFIGS;

export const SUPPORTED_PLATFORMS: Platform[] = [
  'garmin',
  'strava',
  'suunto',
  'coros',
  'polar',
  'decathlon',
];

// Mapping des types d'activités entre notre système et les plateformes
export const ACTIVITY_TYPE_MAPPING = {
  garmin: {
    running: 'RUNNING',
    cycling: 'CYCLING',
    swimming: 'SWIMMING',
    walking: 'WALKING',
    hiking: 'HIKING',
    strength: 'STRENGTH_TRAINING',
    yoga: 'YOGA',
  },
  strava: {
    running: 'Run',
    cycling: 'Ride',
    swimming: 'Swim',
    walking: 'Walk',
    hiking: 'Hike',
    strength: 'WeightTraining',
    yoga: 'Yoga',
  },
  suunto: {
    running: 'Running',
    cycling: 'Cycling',
    swimming: 'Swimming',
    walking: 'Walking',
    hiking: 'Hiking',
    strength: 'Gym',
    yoga: 'Yoga',
  },
  coros: {
    running: 'Run',
    cycling: 'Bike',
    swimming: 'Swim',
    walking: 'Walk',
    hiking: 'Hike',
    strength: 'Strength',
    yoga: 'Yoga',
  },
  polar: {
    running: 'RUNNING',
    cycling: 'CYCLING',
    swimming: 'SWIMMING',
    walking: 'WALKING',
    hiking: 'HIKING',
    strength: 'STRENGTH_TRAINING',
    yoga: 'YOGA',
  },
  decathlon: {
    running: 'running',
    cycling: 'cycling',
    swimming: 'swimming',
    walking: 'walking',
    hiking: 'hiking',
    strength: 'fitness',
    yoga: 'yoga',
  },
};
